# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-30 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='价格')),
                ('bianji', models.CharField(max_length=20, null=True, verbose_name='编辑名字')),
                ('qq', models.CharField(max_length=15, verbose_name='QQ号')),
                ('tel', models.CharField(max_length=15, verbose_name='联系电话')),
                ('site_collected', multiselectfield.db.fields.MultiSelectField(choices=[('知网', '知网'), ('万方', '万方'), ('CQVIP', 'CQVIP'), ('龙源', '龙源')], max_length=14, verbose_name='收录网站')),
                ('words_per_article', models.IntegerField(verbose_name='版面字数')),
                ('level', models.CharField(choices=[('省级', '省级'), ('国家级', '国家级'), ('默认', '默认')], max_length=100, verbose_name='刊物级别')),
            ],
        ),
        migrations.CreateModel(
            name='Qikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=100, verbose_name='期刊DocID')),
                ('book_name_zh', models.CharField(blank=True, default='=暂无=', max_length=100, null=True, verbose_name='期刊中文名称')),
                ('book_name_en', models.CharField(blank=True, default='=暂无=', max_length=100, null=True, verbose_name='期刊英文名称')),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='qikan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='刊物报价', to='web.Qikan'),
        ),
    ]
