# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='价格')),
                ('bianji', models.CharField(max_length=20, null=True, verbose_name='编辑名字')),
                ('qq', models.CharField(max_length=15, verbose_name='QQ号')),
                ('tel', models.CharField(max_length=15, verbose_name='联系电话')),
                ('site_collected', multiselectfield.db.fields.MultiSelectField(choices=[('知网', '知网'), ('万方', '万方'), ('CQVIP', 'CQVIP'), ('龙源', '龙源')], max_length=14, verbose_name='收录网站')),
                ('words_per_article', models.IntegerField(verbose_name='版面字数')),
                ('level', models.CharField(choices=[('省级', '省级'), ('国家级', '国家级'), ('默认', '默认')], max_length=100, verbose_name='刊物级别')),
            ],
        ),
        migrations.CreateModel(
            name='Qikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=50, verbose_name='期刊DocID')),
                ('book_name_zh', models.CharField(blank=True, default='-', max_length=94, null=True, verbose_name='期刊中文名称')),
                ('book_name_en', models.CharField(blank=True, default='-', max_length=157, null=True, verbose_name='期刊英文名称')),
                ('ji_du_jia', models.CharField(blank=True, default='-', max_length=6, null=True, verbose_name='季度价格')),
                ('cn', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='CN')),
                ('you_fa_bian_hao', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='邮发编号')),
                ('quan_nian_jia', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='全年价')),
                ('chu_ban_zhou_qi', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='出版周期')),
                ('feng_mian', models.TextField(blank=True, default='-', null=True, verbose_name='封面')),
                ('fa_xing_nian_fen', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='发行年份')),
                ('ban_nian_jia', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='半年价')),
                ('fa_bao_kan_ju', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='发报刊局')),
                ('chu_ban_ri_qi', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='出版日期')),
                ('jian_jie', models.TextField(blank=True, default='-', null=True, verbose_name='简介')),
                ('url', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='URL')),
                ('dan_jia', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='单价')),
                ('lan_mu', models.TextField(blank=True, default='-', null=True, verbose_name='栏目')),
                ('_from', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='数据来源')),
                ('chu_ban_she', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='出版社')),
                ('fen_lei', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='分类')),
                ('you_xiang', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='邮箱')),
                ('huo_jiang', models.TextField(blank=True, default='-', null=True, verbose_name='获奖')),
                ('you_zheng_bian_ma', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='邮政编码')),
                ('zhu_ban_dan_wei', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='主办单位')),
                ('dian_hua', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='电话')),
                ('zhu_bian', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='主编')),
                ('guan_fang_wang_zhan', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='官方网站')),
                ('is_you_xian_chu_ban', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='是否有限出版')),
                ('is_he_xin', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='是否核心')),
                ('di_zhi', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='地址')),
                ('issn', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='ISSN')),
                ('zhu_guan_dan_wei', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='主管单位')),
                ('xian_yong_kan_ming', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='现用刊名')),
                ('you_fa_dai_hao', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='邮发代号')),
                ('is_du_jia', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='是否独家')),
                ('he_xin_list', models.TextField(blank=True, default='-', null=True, verbose_name='核心列表')),
                ('chu_ban_di', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='出版地')),
                ('chuang_kan_shi_jian', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='创刊时间')),
                ('zong_he_ying_xiang_yin_zi', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='综合影响因子')),
                ('kai_ben', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='开本')),
                ('fu_he_ying_xiang_yin_zi', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='复合影响因子')),
                ('ceng_yong_kan_ming', models.TextField(blank=True, default='-', null=True, verbose_name='曾用刊名')),
                ('shu_ju_ku_shou_lu', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='收录数据库')),
                ('yu_zhong', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='语种')),
                ('ding_jia', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='定价')),
                ('bian_geng', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='变更历史')),
                ('he_xin_lie_biao', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='核心列表')),
                ('guo_wai_shu_ju_ku_shou_lu', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='国外数据库收录')),
                ('ban_mian_fei', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='版面费')),
                ('tou_gao_wang_zhan', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='投稿网站')),
                ('shen_gao_su_du', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='审稿速度')),
                ('lu_yong_bi_li', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='录用比例')),
                ('shen_gao_fei', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='审稿费')),
                ('chu_ban_sheng_fen', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='出版省份')),
                ('duan_jian_jie', models.TextField(blank=True, default='-', null=True, verbose_name='简介')),
                ('isbn', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='ISBN')),
                ('jian_kan_shi_jian', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='见刊时间')),
                ('kuai_jie_fen_lei', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='快捷分类')),
                ('qi_kan_ji_bie', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='期刊级别')),
                ('status', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='发行状态')),
                ('xiang_guan_lian_jie', models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='相关链接')),
                ('za_zhi_she_jie_shao', models.TextField(blank=True, default='-', null=True, verbose_name='杂志社介绍')),
                ('s_code', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='qikan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='刊物报价', to='web.Qikan'),
        ),
    ]
