# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170501_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qikan',
            name='gmt_create',
        ),
        migrations.AlterField(
            model_name='qikan',
            name='_from',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='数据来源'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='ban_mian_fei',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='版面费'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='ban_nian_jia',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='半年价'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='book_name_en',
            field=models.CharField(blank=True, default='=暂无=', max_length=50, null=True, verbose_name='期刊英文名称'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='book_name_zh',
            field=models.CharField(blank=True, default='=暂无=', max_length=50, null=True, verbose_name='期刊中文名称'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='chu_ban_ri_qi',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='出版日期'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='chu_ban_zhou_qi',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='出版周期'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='cn',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='CN'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='dan_jia',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='dian_hua',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='ding_jia',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='定价'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='doc_id',
            field=models.CharField(max_length=50, verbose_name='期刊DocID'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='fa_xing_nian_fen',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='发行年份'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='feng_mian',
            field=models.CharField(blank=True, default='=暂无=', max_length=500, null=True, verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='fu_he_ying_xiang_yin_zi',
            field=models.CharField(blank=True, default='=暂无=', max_length=10, null=True, verbose_name='复合影响因子'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='is_du_jia',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='是否独家'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='is_he_xin',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='是否核心'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='is_you_xian_chu_ban',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='是否有限出版'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='issn',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='ISSN'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='ji_du_jia',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='季度价格'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='lu_yong_bi_li',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='录用比例'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='quan_nian_jia',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='全年价'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='shen_gao_fei',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='审稿费'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='you_fa_bian_hao',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='邮发编号'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='you_fa_dai_hao',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='邮发代号'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='you_zheng_bian_ma',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='邮政编码'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='yu_zhong',
            field=models.CharField(blank=True, default='=暂无=', max_length=20, null=True, verbose_name='语种'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='zhu_guan_dan_wei',
            field=models.CharField(blank=True, default='=暂无=', max_length=50, null=True, verbose_name='主管单位'),
        ),
        migrations.AlterField(
            model_name='qikan',
            name='zong_he_ying_xiang_yin_zi',
            field=models.CharField(blank=True, default='=暂无=', max_length=10, null=True, verbose_name='综合影响因子'),
        ),
    ]
